name: Dart

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        sdk: [stable]
        experimental: [false]
        include:
          - sdk: beta
            experimental: true

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: "Lint: Code formatting"
        run: dart format --output=none --set-exit-if-changed .

      - name: "Lint: Analyze project source"
        run: dart analyze --fatal-warnings .

      - name: "Test: Run tests"
        run: dart test
